services:
  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #   - "6379:6379"
  #   command: redis-server --save 60 1 --loglevel warning
  backend:
    build: .
    container_name: todo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True